import {
    Cloud,
    Zap,
    Shield,
    BarChart3,
    Code,
    Headphones,
    ChevronRight,
    Menu,
    X,
    ArrowRight,
    ArrowLeftRight,
    CheckCircle,
    CheckCircle2,
    Star,
    Users,
    Building,
    Award,
    Target,
    Mail,
    Phone,
    MapPin,
    Info,
    Linkedin,
    Twitter,
    Github,
    ExternalLink,
    Calendar,
    Clock,
    User,
    Tag,
    Smartphone,
    Brain,
    TrendingUp,
    Settings,
    Lightbulb,
    Check,
    Sparkles,
    Globe,
    Package,
    Link as LinkIcon,
    Type,
    AlertCircle,
    Wallet,
    CreditCard,
    Hash,
    Rocket,
    ArrowLeft,
    HeartPulse,
    Activity,
    Plane,
    Heart,
    Dna,
    HandHeart,
    ShieldCheck,
    Stethoscope,
    Infinity,
    BookOpen,
    Scale,
    Microscope,
    UserCheck,
    UserRoundCheck,
    MapPinned,
    CalendarCheck,
    Leaf,
    Eye,
    Sliders,
    Smile,
    Feather,
    Sofa,
    Palette,
    GraduationCap,
    Book,
    Map,
    Atom,
    Layers,
    Droplet,
    Lock,
    ListChecks,
    Link2,
    FlaskConical,
    Syringe,
    AudioWaveform,
    AlignCenter,
    Ear,
    RefreshCw,
    MessageCircle,
  } from "lucide-react";


  const iconMap = {
    // Lucide icons
    cloud: Cloud,
    rocket: Rocket,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    arrowLeftRight: ArrowLeftRight,
    'arrow-left-right': ArrowLeftRight,
    zap: Zap,
    shield: Shield,
    barChart3: BarChart3,
    code: Code,
    headphones: Headphones,
    chevronRight: ChevronRight,
    menu: Menu,
    x: X,
    info: Info,
    checkCircle: CheckCircle,
    checkCircle2: CheckCircle2,
    star: Star,
    users: Users,
    building: Building,
    award: Award,
    target: Target,
    mail: Mail,
    wallet: Wallet,
    hash: Hash,
    creditCard: CreditCard,
    'credit-card': CreditCard,
    phone: Phone,
    smartphone: Smartphone,
    mapPin: MapPin,
    'map-pin': MapPin,
    linkedin: Linkedin,
    twitter: Twitter,
    github: Github,
    externalLink: ExternalLink,
    calendar: Calendar,
    clock: Clock,
    user: User,
    tag: Tag,
    link: LinkIcon,
    link2: Link2,
    'link-2': Link2,
    type: Type,
    alertCircle: AlertCircle,
    heartPulse: HeartPulse,
    'heart-pulse': HeartPulse,
    activity: Activity,
    plane: Plane,
    heart: Heart,
    dna: Dna,
    handHeart: HandHeart,
    'heart-handshake': HandHeart,
    shieldCheck: ShieldCheck,
    'shield-check': ShieldCheck,
    stethoscope: Stethoscope,
    infinity: Infinity,
    bookOpen: BookOpen,
    'book-open': BookOpen,
    scale: Scale,
    microscope: Microscope,
    flaskConical: FlaskConical,
    'flask-conical': FlaskConical,
    userCheck: UserCheck,
    'user-check': UserCheck,
    userRoundCheck: UserRoundCheck,
    'user-round-check': UserRoundCheck,
    mapPinned: MapPinned,
    'map-pinned': MapPinned,
    calendarCheck: CalendarCheck,
    'calendar-check': CalendarCheck,
    leaf: Leaf,
    eye: Eye,
    sliders: Sliders,
    smile: Smile,
    feather: Feather,
    sofa: Sofa,
    palette: Palette,
    graduationCap: GraduationCap,
    'graduation-cap': GraduationCap,
    book: Book,
    map: Map,
    atom: Atom,
    layers: Layers,
    droplet: Droplet,
    lock: Lock,
    listChecks: ListChecks,
    'list-checks': ListChecks,
    // Missing icons for solutions
    'brain-circuit': Brain,
    'arrows-up-from-line': TrendingUp,
    'chart-line': BarChart3,
    'cog': Settings,
    lightbulb: Lightbulb,
    check: Check,
    sparkles: Sparkles,
    globe: Globe,
    package: Package,
    trendingUp: TrendingUp,
    'trending-up': TrendingUp,
    'check-circle': CheckCircle2,
    settings: Settings,
    syringe: Syringe,
    waveform: AudioWaveform,
    audioWaveform: AudioWaveform,
    'audio-waveform': AudioWaveform,
    alignCenter: AlignCenter,
    ear: Ear,
    refreshCw: RefreshCw,
    'refresh-cw': RefreshCw,
    messageCircle: MessageCircle,
    'message-circle': MessageCircle,
    'align-center': AlignCenter,
  };
  
  
  
  export function Icon({ name, size = 24, className }) {
    const IconComponent = iconMap[name];
    
    if (!IconComponent) {
      console.warn(`Icon "${name}" not found`);
      return null;
    }
    
    return <IconComponent size={size} className={className} />;
  }
